name: Update progress

on:
  repository_dispatch:
    types: ["update-progress"]
  

jobs:
  write_and_commit_job:
    runs-on: ubuntu-latest
    name: "Update progress in 2021.yml"
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true

      - name: Edit data
        run: |
          npm install js-yaml
          npm install luxon
          node update-data.js 2021 ${{ github.event.client_payload.date }} ${{ github.event.client_payload.count }}

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Updating progress for ${{ github.event.client_payload.date }}" -a
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_PLANT_083C35810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "Api" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        